import pandas as pd
import glob
import os

# ================= CONFIGURATION =================
OUTPUT_FILENAME = 'nutritrack_complete_db.sql'
USDA_PATTERN = 'USDAFoodsDatabase-*.xlsm'

# Mapping หมวดหมู่ USDA -> NutriTrack Category ID 1-8
# 1=อาหารจานเดียว/เนื้อสัตว์, 2=แป้ง/เส้น, 3=แกง/ต้ม, 4=ผัด/ทอด, 
# 5=ผัก, 6=ผลไม้/ของว่าง, 7=ขนมหวาน, 8=เครื่องดื่ม
CATEGORY_MAP = {
    'Cheese': 1, 'Yogurt': 6, 'Egg': 1, 'Poultry': 1, 'Beef': 1, 'Pork': 1, 'Fish': 1, 'Meat': 1,
    'Fruit': 6, 'Vegetables': 5, 'Legumes': 5, 'Nuts': 6, 'Grains': 2, 'Peanut': 6, 
    'Oil': 4, 'Fat': 4, 'Flour': 2, 'Pasta': 2, 'Rice': 2, 'Bread': 2, 'Cereal': 6,
    'Soup': 3, 'Sauce': 3, 'Beverages': 8, 'Milk': 8, 'Juice': 8, 'Water': 8, 'Sweets': 7, 'Dessert': 7
}

def generate_database():
    print(f"🚀 เริ่มต้นสร้างฐานข้อมูล NutriTrack...")
    sql = []

    # ---------------------------------------------------------
    # PART 1: Database Schema (สร้างตารางตาม ERD)
    # ---------------------------------------------------------
    sql.append("-- ========================================")
    sql.append("-- NutriTrack Complete Database")
    sql.append("-- Generated by NutriTrack Builder")
    sql.append("-- ========================================")
    sql.append("DROP DATABASE IF EXISTS nutritrack;")
    sql.append("CREATE DATABASE nutritrack CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    sql.append("USE nutritrack;")
    sql.append("")

    # 1. Users
    sql.append("""
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role ENUM('admin', 'user') DEFAULT 'user',
    avatar VARCHAR(255),
    weight DECIMAL(5,2),
    height DECIMAL(5,2),
    age INT,
    gender ENUM('male', 'female'),
    activity_level ENUM('sedentary', 'light', 'moderate', 'active', 'very_active') DEFAULT 'moderate',
    goal ENUM('lose', 'maintain', 'gain') DEFAULT 'maintain',
    daily_calories INT DEFAULT 2000,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);""")

    # 2. Categories
    sql.append("""
CREATE TABLE categories (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(10),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);""")

    # 3. Nutrients Reference
    sql.append("""
CREATE TABLE nutrients (
    id INT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(50) UNIQUE NOT NULL,
    name_th VARCHAR(100),
    name_en VARCHAR(100),
    unit VARCHAR(20),
    daily_value DECIMAL(10,2),
    category ENUM('macro', 'vitamin', 'mineral', 'other') DEFAULT 'other'
);""")

    # 4. Foods (รองรับ USDA และ อาหารไทย)
    sql.append("""
CREATE TABLE foods (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    name_en VARCHAR(255),
    brand VARCHAR(100),         
    barcode VARCHAR(50),        
    calories INT NOT NULL DEFAULT 0,
    protein DECIMAL(6,2) DEFAULT 0,
    carbs DECIMAL(6,2) DEFAULT 0,
    fat DECIMAL(6,2) DEFAULT 0,
    fiber DECIMAL(6,2) DEFAULT 0,
    serving_size VARCHAR(100),
    image_url VARCHAR(500),
    category_id INT,
    source VARCHAR(50) DEFAULT 'system',
    external_id VARCHAR(100),   
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'approved',
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);""")

    # 5. Food Nutrients (สารอาหารละเอียด)
    sql.append("""
CREATE TABLE food_nutrients (
    id INT PRIMARY KEY AUTO_INCREMENT,
    food_id INT NOT NULL,
    nutrient_id INT NOT NULL,
    amount DECIMAL(10,4) NOT NULL,
    FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE CASCADE,
    FOREIGN KEY (nutrient_id) REFERENCES nutrients(id) ON DELETE CASCADE
);""")

    # 6. Meal Plans
    sql.append("""
CREATE TABLE meal_plans (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_date (user_id, date)
);""")

    # 7. Meal Items
    sql.append("""
CREATE TABLE meal_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    meal_plan_id INT NOT NULL,
    food_id INT NOT NULL,
    meal_type ENUM('breakfast', 'lunch', 'dinner', 'snacks') NOT NULL,
    quantity DECIMAL(5,2) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (meal_plan_id) REFERENCES meal_plans(id) ON DELETE CASCADE,
    FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE CASCADE
);""")

    # 8. Food Logs (บันทึกการกินจริง)
    sql.append("""
CREATE TABLE food_logs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    food_id INT NOT NULL,
    meal_type ENUM('breakfast', 'lunch', 'dinner', 'snacks') NOT NULL,
    quantity DECIMAL(5,2) DEFAULT 1,
    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE CASCADE
);""")

    # 9. Posts (Community)
    sql.append("""
CREATE TABLE posts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    content TEXT NOT NULL,
    image_url VARCHAR(255),
    likes INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);""")

    # 10. Comments
    sql.append("""
CREATE TABLE comments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);""")

    # 11. Achievements
    sql.append("""
CREATE TABLE achievements (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    badge_type VARCHAR(50) NOT NULL,
    earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_badge (user_id, badge_type)
);""")

    # 12. Portion Sizes (หน่วยวัดเพิ่มเติม)
    sql.append("""
CREATE TABLE portion_sizes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    food_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    grams DECIMAL(8,2) NOT NULL,
    FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE CASCADE
);""")

    # ---------------------------------------------------------
    # PART 2: Seed Data (ข้อมูลตั้งต้น)
    # ---------------------------------------------------------
    print("🔹 กำลังเพิ่มข้อมูลพื้นฐาน (Users, Categories, Nutrients)...")
    
    # Users (Admin & User)
    sql.append("INSERT INTO users (id, email, password, name, role, daily_calories) VALUES (1, 'admin@nutritrack.com', '$2b$10$hashed_password_here', 'Admin NutriTrack', 'admin', 2000);")
    sql.append("INSERT INTO users (id, email, password, name, role, daily_calories) VALUES (2, 'user@nutritrack.com', '$2b$10$hashed_password_here', 'User NutriTrack', 'user', 2000);")

    # Categories (8 หมวดหลัก)
    sql.append("""
INSERT INTO categories (id, name, icon) VALUES 
(1, 'อาหารจานเดียว/เนื้อสัตว์', 'mw'), (2, 'ข้าว/เส้น/แป้ง', 'cw'), (3, 'แกง/ต้ม', 'sw'), (4, 'ผัด/ทอด/ไขมัน', 'fw'),
(5, 'ผัก/สลัด', 'vw'), (6, 'ผลไม้/ของว่าง', 'fr'), (7, 'ขนมหวาน', 'dw'), (8, 'เครื่องดื่ม', 'bw');""")

    # Nutrients (Reference)
    sql.append("""
INSERT INTO nutrients (code, name_th, name_en, unit, daily_value, category) VALUES
('ENERGY', 'พลังงาน', 'Energy', 'kcal', 2000, 'macro'),
('PROTEIN', 'โปรตีน', 'Protein', 'g', 50, 'macro'),
('FAT', 'ไขมัน', 'Total Fat', 'g', 78, 'macro'),
('CARBS', 'คาร์โบไฮเดรต', 'Carbohydrates', 'g', 275, 'macro'),
('FIBER', 'ใยอาหาร', 'Fiber', 'g', 28, 'macro'),
('SUGAR', 'น้ำตาล', 'Sugars', 'g', 50, 'macro'),
('SODIUM', 'โซเดียม', 'Sodium', 'mg', 2300, 'mineral'),
('CALCIUM', 'แคลเซียม', 'Calcium', 'mg', 1000, 'mineral'),
('IRON', 'ธาตุเหล็ก', 'Iron', 'mg', 18, 'mineral'),
('VITC', 'วิตามินซี', 'Vitamin C', 'mg', 90, 'vitamin'),
('VITA', 'วิตามินเอ', 'Vitamin A', 'mcg', 900, 'vitamin'),
('VITD', 'วิตามินดี', 'Vitamin D', 'mcg', 20, 'vitamin');""")

    # อาหารไทย (Sample Data)
    thai_foods = [
        "('ข้าวมันไก่', 'Hainanese Chicken Rice', 600, 30, 65, 22, 1, '1 จาน', 1, 'THAI', 'approved')",
        "('ข้าวผัดกะเพราหมูสับ', 'Basil Pork with Rice', 520, 22, 58, 20, 2, '1 จาน', 1, 'THAI', 'approved')",
        "('ต้มยำกุ้ง', 'Tom Yum Kung', 180, 22, 8, 6, 2, '1 ถ้วย', 3, 'THAI', 'approved')",
        "('ส้มตำไทย', 'Papaya Salad', 120, 4, 18, 4, 4, '1 จาน', 5, 'THAI', 'approved')",
        "('กาแฟลาเต้', 'Latte', 190, 10, 18, 7, 0, '1 แก้ว', 8, 'THAI', 'approved')"
    ]
    for tf in thai_foods:
        sql.append(f"INSERT INTO foods (name, name_en, calories, protein, carbs, fat, fiber, serving_size, category_id, source, status) VALUES {tf};")

    # ---------------------------------------------------------
    # PART 3: USDA Foods (จากไฟล์ Excel)
    # ---------------------------------------------------------
    print("🔹 กำลังประมวลผลไฟล์ USDA Excel...")
    files = sorted(glob.glob(USDA_PATTERN))
    
    if files:
        all_data = []
        for f in files:
            try:
                df = pd.read_excel(f, sheet_name='NAI')
                df.columns = [c.strip() for c in df.columns]
                if 'USDA Foods Material Code' in df.columns:
                    all_data.append(df)
            except: pass
        
        if all_data:
            full_df = pd.concat(all_data, ignore_index=True)
            # ลบตัวซ้ำ (เอาข้อมูลล่าสุด)
            full_df.drop_duplicates(subset=['USDA Foods Material Code'], keep='last', inplace=True)
            
            count = 0
            for _, row in full_df.iterrows():
                try:
                    mat_code = str(row['USDA Foods Material Code'])
                    name = str(row.get('USDA Foods Products Description', '')).replace("'", "\\'")
                    brand = str(row.get('Brand Name', '')).replace("'", "\\'").replace("nan", "")
                    gtin = str(row.get('gtin', '')).replace("nan", "").split('.')[0]
                    
                    full_name = f"{name} ({brand})" if brand else name
                    
                    cat_raw = str(row.get('Food Category', ''))
                    cat_id = 'NULL'
                    for k, v in CATEGORY_MAP.items():
                        if k in cat_raw: cat_id = v; break
                    
                    def get_v(c): 
                        v = row.get(c); return float(v) if pd.notnull(v) else 0

                    cal = int(get_v('Calories (kcal) per Serving'))
                    prot = get_v('Protein (g) per Serving')
                    fat = get_v('Total Fat (g) per Serving')
                    carbs = get_v('Total Carbohydrate (g) per Serving')
                    fiber = get_v('Dietary Fiber (g) per Serving')
                    serving = f"{row.get('Serving Size','')} {row.get('Serving Unit of Measure','')}".replace("nan","").strip()

                    sql.append(f"INSERT INTO foods (name, name_en, brand, barcode, calories, protein, carbs, fat, fiber, serving_size, category_id, source, external_id, status, created_by) "
                               f"VALUES ('{full_name}', '{full_name}', '{brand}', '{gtin}', {cal}, {prot}, {carbs}, {fat}, {fiber}, '{serving}', {cat_id}, 'USDA', '{mat_code}', 'approved', 1);")
                    
                    # เพิ่ม Micronutrients (ตัวอย่าง: Calcium)
                    calcium = get_v('Calcium, Ca (mg) per Serving')
                    if calcium > 0:
                        sql.append(f"INSERT INTO food_nutrients (food_id, nutrient_id, amount) SELECT id, (SELECT id FROM nutrients WHERE code='CALCIUM'), {calcium} FROM foods WHERE source='USDA' AND external_id='{mat_code}';")
                    
                    count += 1
                except: continue
            print(f"   ✅ เพิ่มสินค้า USDA สำเร็จ {count} รายการ")

    # บันทึกไฟล์
    with open(OUTPUT_FILENAME, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql))
    
    print(f"🎉 เสร็จสมบูรณ์! ไฟล์ {OUTPUT_FILENAME} พร้อมใช้งานแล้ว")

if __name__ == "__main__":
    generate_database()
