import pandas as pd
import glob
import os

# --- Configuration ---
# ค้นหาไฟล์ Excel ทั้งหมดที่ขึ้นต้นด้วย USDAFoodsDatabase
INPUT_PATTERN = 'USDAFoodsDatabase-*.xlsm'
OUTPUT_FILE = 'nutritrack_seed_usda_schools_full.sql'

# Mapping Category (USDA Group -> NutriTrack Category ID 1-8)
CATEGORY_MAP = {
    'Cheese': 1, 'Yogurt': 6, 'Egg products': 1,
    'Poultry': 1, 'Beef': 1, 'Pork': 1, 'Fish': 1,
    'Fruit': 6, 'Vegetables': 5, 'Legumes': 5,
    'Nuts and seeds': 6, 'Grains': 2
}

def generate_consolidated_sql():
    files = glob.glob(INPUT_PATTERN)
    if not files:
        print("No files found!")
        return

    print(f"Found {len(files)} files. Starting consolidation...")
    
    all_data = []

    # 1. Loop through all files
    for file in files:
        print(f"Reading {file}...")
        try:
            df = pd.read_excel(file, sheet_name='NAI')
            # เลือกเฉพาะ Columns ที่จำเป็นเพื่อลดขนาด
            cols = [
                'USDA Foods Material Code', 'USDA Foods Products Description', 'Brand Name', 
                'gtin', 'Food Category', 'Serving Size', 'Serving Unit of Measure',
                'Calories (kcal) per Serving', 'Protein (g) per Serving', 
                'Total Fat (g) per Serving', 'Total Carbohydrate (g) per Serving', 
                'Dietary Fiber (g) per Serving', 'Calcium, Ca (mg) per Serving ', 
                'Iron, Fe (mg) per Serving', 'Potassium, K (mg) per Serving', 
                'Sodium (mg) per Serving', 'Sugars (g) per Serving', 'Vitamin D (mcg) per Serving'
            ]
            # กรองเฉพาะ Column ที่มีอยู่จริง (บางไฟล์อาจชื่อต่างกันเล็กน้อย)
            valid_cols = [c for c in cols if c in df.columns]
            all_data.append(df[valid_cols])
        except Exception as e:
            print(f"Error reading {file}: {e}")

    # 2. Combine and Deduplicate
    full_df = pd.concat(all_data, ignore_index=True)
    initial_count = len(full_df)
    
    # ลบตัวซ้ำโดยดูจาก 'USDA Foods Material Code' และ 'gtin'
    # เก็บแถวล่าสุดไว้ (keep='last') เพราะข้อมูลเดือนล่าสุดน่าจะ Update ที่สุด
    full_df.drop_duplicates(subset=['USDA Foods Material Code'], keep='last', inplace=True)
    
    print(f"Consolidated: {initial_count} items -> Unique: {len(full_df)} items")

    # 3. Generate SQL
    sql_lines = [
        "-- USDA Foods (School/Commercial Products) 12-Month Consolidated Data",
        "-- Generated by import_usda_schools.py",
        "",
        "USE nutritrack;",
        ""
    ]
    
    for _, row in full_df.iterrows():
        material_code = str(row.get('USDA Foods Material Code', ''))
        desc = str(row.get('USDA Foods Products Description', '')).replace("'", "\\'")
        brand = str(row.get('Brand Name', '')).replace("'", "\\'")
        gtin = str(row.get('gtin', ''))
        
        full_name = f"{desc} ({brand})"
        serving = f"{row.get('Serving Size','')} {row.get('Serving Unit of Measure','')}"
        cat_id = CATEGORY_MAP.get(row.get('Food Category'), 'NULL')

        # Helper for float values
        def get_val(col):
            val = row.get(col)
            try: return float(val) if pd.notnull(val) else 0
            except: return 0

        cal = int(get_val('Calories (kcal) per Serving'))
        prot = get_val('Protein (g) per Serving')
        fat = get_val('Total Fat (g) per Serving')
        carbs = get_val('Total Carbohydrate (g) per Serving')
        fiber = get_val('Dietary Fiber (g) per Serving')

        # Insert Food
        sql = (f"INSERT INTO foods (name, name_en, brand, barcode, calories, protein, carbs, fat, fiber, "
               f"serving_size, category_id, source, external_id, status, created_by) VALUES "
               f"('{full_name}', '{full_name}', '{brand}', '{gtin}', {cal}, {prot}, {carbs}, {fat}, {fiber}, "
               f"'{serving}', {cat_id}, 'USDA_SCHOOLS', '{material_code}', 'approved', 1);")
        sql_lines.append(sql)

        # Insert Micronutrients
        micros = {
            'CALCIUM': 'Calcium, Ca (mg) per Serving ',
            'IRON': 'Iron, Fe (mg) per Serving',
            'POTASSIUM': 'Potassium, K (mg) per Serving',
            'SODIUM': 'Sodium (mg) per Serving',
            'SUGAR': 'Sugars (g) per Serving',
            'VITD': 'Vitamin D (mcg) per Serving'
        }
        
        for code, col in micros.items():
            amount = get_val(col)
            if amount > 0:
                sql_n = (f"INSERT INTO food_nutrients (food_id, nutrient_id, amount) "
                         f"SELECT id, (SELECT id FROM nutrients WHERE code='{code}'), {amount} "
                         f"FROM foods WHERE source='USDA_SCHOOLS' AND external_id='{material_code}';")
                sql_lines.append(sql_n)
        
        sql_lines.append("")

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))
    
    print(f"Success! Generated {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_consolidated_sql()
