-- NutriTrack Seed Data: USDA Foods (Master Consolidated)
-- Source: USDA Foods Database 2024-2025 (24 Months)
-- Generated by NutriTrack Auto-Importer

USE nutritrack;

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Potatoes, Wedges, Low-sodium, Frozen (IQF)', 80, 1.0, 16.0, 2.0, 1.0, '76 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Potatoes, Oven Fries, Low-sodium, Frozen', 70, 1.0, 12.0, 2.5, 1.0, '56 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Ham, 97% Fat Free, Water-Added, Cooked, Frozen', 50, 9.0, 1.0, 1.0, 0.0, '57 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Mozzarella, Lite, Shredded, Frozen', 60, 8.0, 1.0, 3.0, 1.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Breast, Sliced, Frozen', 70, 12.0, 1.0, 1.0, 0.0, '56 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Breast, Smoked, Sliced, Frozen', 60, 12.0, 1.0, 1.0, 0.0, '56 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Ham, Smoked, Sliced, Frozen', 60, 9.0, 2.0, 1.5, 0.0, '57 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Chicken, Diced, Cooked, Frozen', 130, 19.0, 1.0, 6.0, 0.0, '84 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Chicken, Oven Roasted, Cut-up, Cooked, Frozen', 160, 18.0, 0.0, 9.0, 0.0, '84 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Chicken, Cut-up, Raw, Frozen', 250, 19.0, 0.0, 19.0, 0.0, '112 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Cheddar, White, Shredded, Chilled', 110, 6.0, 1.0, 9.0, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Cheddar, Yellow, Shredded, Chilled', 110, 7.0, 0.0, 9.0, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Cheddar, Yellow, Reduced Fat, Shredded, Chilled', 90, 8.0, 1.0, 6.0, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, American, Yellow, Pasteurized, Loaves, Chilled', 100, 5.0, 2.0, 9.0, 0.0, '28.35 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, American, Yellow, Pasteurized, Sliced, Chilled', 100, 5.0, 2.0, 9.0, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Mozzarella, Low Moisture Part Skim, Shredded, Frozen', 80, 7.0, 2.0, 5.0, 1.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Mozzarella, Low Moisture Part Skim, Loaves, Frozen', 80, 7.0, 1.0, 5.0, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Blended American, Yellow, Reduced Fat, Sliced, Chilled', 70, 5.0, 4.0, 4.5, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Blended American, White, Reduced Fat, Sliced, Chilled', 70, 5.0, 4.0, 4.5, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Eggs, Liquid Whole, Frozen', 70, 6.0, 1.0, 4.5, 0.0, '50 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Chicken, Fajita Seasoned Strips, Cooked, Frozen', 120, 16.0, 1.32, 5.93, 0.22, '84 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Taco Filling, Cooked, Frozen', 167, 15.76, 5.26, 9.25, 1.63, '97.524 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Breast, Frozen', 70, 12.0, 1.0, 1.5, 0.0, '56 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Breast, Smoked, Frozen', 60, 12.0, 1.0, 0.5, 0.0, '56 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Roast, Raw, Frozen', 160, 20.0, 0.0, 8.0, 0.0, '112 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Ham, Smoked, Frozen', 60, 9.0, 2.0, 1.5, 0.0, '57 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Coarse Ground, Cooked, Canned', 120, 10.0, 0.0, 8.0, 0.0, '56 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Crumbles w/SPP, Cooked, Frozen', 109, 10.5, 1.2, 6.9, 0.8, '56.7 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pork, Coarse Ground, Cooked, Canned', 120, 9.0, 0.0, 8.0, 0.0, '56 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Fine Ground, 100%, 85/15, Raw, Frozen', 240, 22.0, 0.0, 17.0, 0.0, '112 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Patties, Lean, Raw, 2.0 MMA, Frozen', 100, 15.0, 2.0, 3.5, 0.0, '88 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Ham, 97% Fat Free, Water-Added, Cooked, Sliced, Frozen', 50, 9.0, 1.0, 1.0, 0.0, '57 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Tuna, Chunk Light, Canned (K)', 80, 16.0, 1.0, 1.0, 0.0, '85 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Apple Slices, Unsweetened, Canned', 60, 0.0, 14.0, 0.0, 2.0, '125 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Mixed Fruit (Peaches, Pears, Grapes), Extra Light Syrup, Canned', 66, 0.51, 16.33, 0.21, 1.7, '124 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Apricots, Diced, Extra Light Syrup, Canned', 60, 1.0, 15.0, 0.0, 1.0, '124 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peaches, Sliced, Extra Light Syrup, Canned', 60, 1.0, 16.0, 0.0, 1.0, '124 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peaches, Diced, Extra Light Syrup, Canned', 60, 1.0, 16.0, 0.0, 1.0, '124 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pears, Sliced, Extra Light Syrup, Canned', 70, 0.0, 17.0, 0.0, 3.0, '128 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pears, Diced, Extra Light Syrup, Canned (K)', 70, 0.0, 18.0, 0.0, 3.0, '128 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pears, Halves, Extra Light Syrup, Canned', 70, 0.0, 17.0, 0.0, 3.0, '128 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peaches, Sliced, Frozen', 80, 1.0, 19.0, 0.0, 2.0, '140 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peaches, Sliced, Frozen', 84, 0.0, 21.0, 0.0, 2.0, '125 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peaches, Diced, Cups, Frozen', 80, 1.0, 21.0, 0.0, 2.0, '125 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Blueberries, Wild, Unsweetened, Frozen', 80, 0.0, 19.0, 0.0, 6.0, '140 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Blueberries, Wild, Unsweetened, Frozen', 40, 0.0, 9.0, 0.0, 3.0, '70 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Strawberries, Sliced, Frozen', 45, 1.0, 11.0, 0.0, 1.0, '70 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Strawberries, Diced, Cups, Frozen', 80, 1.0, 19.0, 0.0, 2.0, '128 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Apricots, Diced, Cups, Frozen', 110, 1.0, 25.0, 0.0, 2.0, '128 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Orange Juice, Unsweetened, Cartons, Frozen', 60, 0.0, 14.0, 0.0, 0.0, '118 milliliters MLT', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Raisins, Unsweetened, Individual Portion', 110, 1.0, 32.0, 0.0, 2.0, '37.7 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Green, Low-sodium, Canned (K)', 15, 1.0, 3.0, 0.0, 1.0, '120 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Carrots, Sliced, Low-sodium, Canned', 20, 0.0, 4.0, 0.0, 1.0, '120 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Corn, Whole Kernel, No Salt Added, Canned (K)', 60, 1.0, 9.0, 0.5, 1.0, '125 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peas, Green, Low-sodium, Canned', 60, 3.0, 11.0, 0.0, 3.0, '125 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Sweet Potatoes, Light Syrup, No Salt Added, Canned', 130, 0.0, 34.0, 0.0, 4.0, '160 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Tomato Paste, No Salt Added, Canned', 25, 1.0, 6.0, 0.0, 1.0, '30 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Tomatoes, Diced, No Salt Added, Canned', 25, 1.0, 5.0, 0.0, 1.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Salsa, Low-sodium, Canned', 35, 2.0, 7.0, 0.0, 2.0, '123 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Tomato Sauce, Low-sodium, Canned', 40, 2.0, 9.0, 0.0, 2.0, '123 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Spaghetti Sauce, Low-sodium, Canned', 35, 2.0, 8.0, 0.0, 2.0, '125 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Corn, Whole Kernel, No Salt Added, Frozen', 80, 3.0, 15.0, 1.0, 3.0, '93 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peas, Green, No Salt Added, Frozen', 80, 5.0, 13.0, 0.0, 5.0, '93 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Green, No Salt Added, Frozen', 35, 2.0, 7.0, 0.0, 2.0, '89 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Carrots, Sliced, No Salt Added, Frozen', 30, 0.0, 7.0, 0.0, 3.0, '86 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Potatoes, Wedges, Fat Free, Low-sodium, Frozen (IQF)', 90, 2.0, 21.0, 0.0, 2.0, '100 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Black, Low-sodium, Canned', 110, 2.0, 19.0, 1.0, 7.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Garbanzo, Low-sodium, Canned (K)', 110, 6.0, 18.0, 1.0, 6.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Refried, Low-sodium, Canned', 140, 8.0, 24.0, 1.5, 6.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Vegetarian, Low-sodium, Canned', 130, 6.0, 20.0, 0.0, 4.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Pinto, Low-sodium, Canned', 80, 8.0, 19.0, 0.0, 7.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Small Red, Low-sodium, Canned', 110, 6.0, 20.0, 0.5, 9.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Black-eyed Pea, Low-sodium, Canned', 90, 5.0, 14.0, 0.0, 4.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Pink, Low-sodium, Canned', 80, 5.0, 16.0, 0.0, 7.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Kidney, Dark Red, Low-sodium, Canned', 75, 8.0, 14.0, 0.0, 5.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Baby Lima, Low-sodium, Canned', 110, 9.0, 20.0, 0.0, 5.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Great Northern, Low-sodium, Canned', 80, 6.0, 15.0, 0.0, 5.0, '130 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Pinto, Dry', 225, 19.3, 62.43, 1.72, 32.8, '100 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peanut Butter, Smooth', 180, 7.0, 8.0, 15.0, 2.0, '32 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Flour, All Purpose, Enriched, Bleached', 110, 3.0, 23.0, 0.0, 1.0, '30 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pasta, Spaghetti, Enriched', 200, 7.0, 42.0, 1.0, 2.0, '56 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Oats, Rolled, Quick Cooking', 150, 5.0, 27.0, 2.5, 4.0, '40 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Rice, Long Grain, Parboiled', 170, 4.0, 37.0, 0.0, 0.0, '47 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Rice, Brown, Long Grain, Parboiled', 150, 3.0, 32.0, 1.0, 1.0, '44 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Rice, Brown, Long Grain, Parboiled', 150, 3.0, 32.0, 1.0, 1.0, '44 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Spaghetti Sauce, Low-sodium, Pouch', 35, 2.0, 8.0, 0.0, 2.0, '124 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Salsa, Low-sodium, Pouch', 35, 2.0, 8.0, 0.0, 2.0, '125 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Tomato Sauce, Low-sodium, Pouch', 40, 2.0, 9.0, 0.0, 2.0, '120 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Flour, White Whole Wheat/Enriched 60/40 Blend', 100, 3.0, 23.0, 0.5, 4.0, '30 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Flour, White Whole Wheat/Enriched 60/40 Blend', 100, 3.0, 23.0, 0.5, 4.0, '30 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Fine Ground, 100%, 85/15, LFTB OPT, Raw, Frozen', 240, 22.0, 0.0, 17.0, 0.0, '112 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Patties w/SPP, Cooked, 2.0 MMA, Frozen', 118, 11.16, 1.86, 6.82, 1.2, '62 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Patties, 100%, 90/10, Raw, 2.0 MMA, Frozen', 130, 15.0, 0.0, 8.0, 0.0, '80 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Patties, 100%, 85/15, Raw, 2.0 MMA, Frozen', 172, 15.0, 0.0, 12.0, 0.0, '80 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Applesauce, Unsweetened, Cups, Shelf-Stable', 50, 0.0, 14.0, 0.0, 1.0, '128 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pancakes, Whole Grain or Whole Grain-Rich, Frozen', 130, 4.0, 26.0, 2.0, 3.0, '68 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Tortillas, Whole Grain or Whole Grain-Rich, 8 inch, Frozen', 110, 3.0, 18.0, 3.0, 3.0, '44 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Mozzarella, Low Moisture Part Skim, String, Chilled', 90, 7.0, 1.0, 6.0, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Yogurt, High-Protein, Blueberry, Chilled (K)', 90, 9.0, 13.0, 0.0, 1.0, '113 GRM', 6, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Yogurt, High-Protein, Strawberry, Chilled (K)', 90, 9.0, 12.0, 0.0, 1.0, '113 GRM', 6, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Yogurt, High-Protein, Vanilla, Chilled (K)', 80, 9.0, 11.0, 0.0, 0.0, '113 GRM', 6, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Spinach, Chopped, No Salt Added, Frozen (IQF)', 31, 4.0, 4.0, 1.0, 3.0, '113 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Chicken, Unseasoned Grilled Strips, Cooked, Frozen', 92, 19.32, 0.0, 1.68, 0.0, '84 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Broccoli Florets, No Salt Added, Frozen', 25, 3.0, 5.0, 0.0, 3.0, '85 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Carrots, Diced, No Salt Added, Frozen', 30, 0.0, 8.0, 0.0, 2.0, '85 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pasta, Macaroni, Whole Grain-Rich Blend', 200, 7.0, 41.0, 1.5, 5.0, '56 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pasta, Rotini, Whole Grain-Rich Blend', 200, 7.0, 41.0, 1.5, 5.0, '56 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pasta, Spaghetti, Whole Grain-Rich Blend', 200, 7.0, 41.0, 1.5, 5.0, '56 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pasta, Penne, Whole Grain-Rich Blend', 200, 7.0, 41.0, 1.0, 1.0, '56 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Applesauce, Unsweetened, Canned (K)', 60, 0.0, 15.0, 0.0, 1.0, '135 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Sweet Potatoes, Cubes, No Salt Added, Frozen', 80, 1.0, 18.0, 0.0, 3.0, '100 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Blueberries, Unsweetened, Frozen', 40, 0.33, 9.49, 0.5, 2.1, '78 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Blueberries, Unsweetened, Frozen', 40, 0.33, 9.49, 0.5, 2.1, '78 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Orange Juice, Unsweetened, Cups, Frozen', 60, 0.0, 14.0, 0.0, 0.0, '118 milliliters MLT', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beef, Patties, Cooked, 2.0 MMA, Frozen', 130, 11.0, 0.531, 8.0, 0.054, '62 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Sweet Potatoes, Crinkle Cut Fries, Low-Sodium, Frozen', 130, 2.0, 19.0, 5.0, 4.0, '85 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cranberries, Dried, Individual Portion', 110, 0.0, 27.0, 0.0, 2.0, '32.9 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pepper/Onion Strips, No Salt Added, Frozen', 30, 1.0, 7.0, 0.0, 1.0, '100 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Pork, Pulled, Cooked, Frozen', 120, 14.0, 0.0, 7.0, 0, '84 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peas, Green, No Salt Added, Frozen', 70, 4.0, 12.0, 0.0, 4.0, '89 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Potatoes, Diced, No Salt Added, Frozen', 82, 2.0, 17.0, 0.0, 1.0, '100 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Eggs, Liquid Whole, Frozen', 70, 6.0, 1.0, 4.5, 0.0, '50 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Strawberries, Whole, Unsweetened, Frozen (IQF)', 25, 0.0, 6.0, 0.0, 1.0, '70 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Alaska Pollock, Whole Grain-Rich Breaded Sticks, Frozen', 220, 16.0, 20.0, 9.0, 2.0, '113 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Peanut Butter, Individual Portion, Smooth', 200, 7.0, 4.0, 16.0, 2.0, '31.2 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Flour, 100% White Whole Wheat', 110, 4.0, 22.0, 0.5, 4.0, '30 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Mixed Berries (Blueberries, Strawberries), Cups, Frozen', 70, 1.0, 19.0, 0.0, 3.0, '113 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Strawberries, Sliced, Unsweetened, Frozen (IQF)', 25, 0.0, 6.0, 0.0, 1.0, '70 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cherries, Sweet, Pitted, Unsweetened, Frozen (IQF)', 90, 1.0, 22.0, 0.0, 3.0, '140 GRM', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Chicken, Grilled Fillet, 2.0 MMA, Cooked, Frozen', 100, 18.0, 1.0, 2.5, 0.0, '81 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Carrots, Diced, No Salt Added, Frozen', 30, 1.0, 8.0, 0.0, 2.0, '85 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Corn, Whole Kernel, No Salt Added, Frozen', 100, 2.0, 21.0, 1.0, 2.0, '90 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Beans, Green, No Salt Added, Frozen', 35, 1.4, 7.1, 0.0, 2.3, '81 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Cheddar, Yellow, Sliced, Chilled', 80, 5.0, 0.0, 7.0, 0.0, '21 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Cheese, Pepper Jack, Shredded, Chilled', 100, 6.0, 1.0, 8.0, 0.0, '28 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Mixed Vegetables, No Salt Added, Frozen', 50, 2.0, 11.0, 0.0, 3.0, '90 GRM', 2, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Yogurt, High-Protein, Vanilla, Chilled (K)', 130, 15.0, 18.0, 0.0, 1.0, '170 GRM', 6, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Eggs, Patties, Cooked, 1.0 MMA, Round, Frozen', 60, 4.0, 1.0, 4.5, 0.0, '35 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Apple Juice, 100%, Unsweetened, Cups, Frozen', 60, 0.0, 14.0, 0.0, 0.0, '118 milliliters MLT', 5, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Chicken, Pulled, Cooked, Frozen', 100, 19.0, 1.0, 2.0, 0.0, '84 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Breast, Smoked, Sliced, Frozen', 60, 12.0, 1.0, 1.0, 0.0, '56 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Ham, Smoked, Sliced, Frozen', 60, 9.0, 2.0, 1.5, 0.0, '57 GRM', 1, 'approved', 1);

INSERT INTO foods (name, calories, protein, carbs, fat, fiber, serving_size, category_id, status, created_by) VALUES ('Turkey, Deli Breast, Sliced, Frozen', 70, 12.0, 1.0, 1.0, 0.0, '56 GRM', 1, 'approved', 1);
